//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filtration.Parser.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filtration.Parser.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Item Filter Script created by Filtration v0.1 - www.github.com/XVar/filtration
        ///# Begin Script Description
        ///# This is a test script
        ///# 
        ///# End Script Description
        ///
        ///# First test condition booyah
        ///Show
        ///    ItemLevel = 32
        ///    DropLevel &gt;= 85
        ///    Quality &gt;= 15
        ///    Sockets &lt; 4
        ///    LinkedSockets &gt;= 3
        ///    SetFontSize 12
        ///	
        ///# Section: Gud stuff u shud pick up m9
        ///
        ///# Second test condition
        ///Show
        ///    ItemLevel &gt; 50
        ///    Quality &gt;= 15
        ///    Rarity &gt; Magic
        ///    Class &quot;Test Class 1&quot; &quot;Test Class 2&quot; &quot;Test Class  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testscript {
            get {
                return ResourceManager.GetString("testscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Script description
        ///#Script description
        ///#Script description
        ///#Script description
        ///
        ///#Comment
        ///#SomeComment
        ///
        ///#Blockdescription
        ///Show	#Flasks - Endgame - Life/Mana - Divine/Eternal - Q10+ - Normal
        ///	Class &quot;Life Flasks&quot; &quot;Mana Flasks&quot;
        ///	Rarity Normal
        ///	DropLevel &gt;= 60
        ///	Quality &gt;= 10
        ///	SetFontSize 28
        ///	SetTextColor 240 240 240	#Normal Item Highlight
        ///
        ///#commentymccommentface
        ///    
        ///Show	#Flasks - Endgame - Life/Mana - Divine/Eternal - Q10+ - Normal
        ///	Class &quot;Life Flasks&quot; &quot;Mana Flasks&quot;
        ///	Rarity Normal
        ///	DropL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testscript2 {
            get {
                return ResourceManager.GetString("testscript2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###BETA VERSION 1.0.0.1-8
        ///#Please test and let me know via pm on reddit /u/brute_force or @Thiole in game if i am online
        ///
        ///#------------------------------------------------------------------
        ///#Fishing Rods First OFC
        ///Show
        ///    Class Fishing Rods
        ///    SetTextColor 0 0 0
        ///    SetBorderColor 0 0 0
        ///    SetBackgroundColor 255 255 255
        ///	
        ///Show 
        ///	Class &quot;Quest Items&quot;
        ///	
        ///#####Shows better currency differently from lower currency for efficiency
        ///##### skill gems
        ///Show
        ///    Class &quot;Active Skill Gems&quot; &quot;Support Skil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ThioleItemFilter {
            get {
                return ResourceManager.GetString("ThioleItemFilter", resourceCulture);
            }
        }
    }
}
